services:
  db:
    image: mysql:8.0-bookworm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: ./db/tabcreate.sql
        target: /docker-entrypoint-initdb.d/000-tabcreate.sql
      - type: bind
        source: ./db/usercreate.sql
        target: /docker-entrypoint-initdb.d/001-usercreate.sql
      - type: bind
        source: ./cdsagenda-4.2.9/dbutil/tabfill.sql
        target: /docker-entrypoint-initdb.d/002-tabfill.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    ports:
      - 9090:9090
